[program:stardate-rs-worker]
command=/home/x/Dropbox/2/src/rust/stardate-rs-worker/target/debug/stardate-rs-worker
directory=/home/x/Dropbox/2/src/rust/stardate-rs-worker
user=x
autostart=true
autorestart=true
stderr_logfile=/var/log/rs-worker/stardate.err.log
stdout_logfile=/var/log/rs-worker/stardate.out.log
