/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 50854d68-d21a-4e78-928d-f3590661539a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the expansion of the expected value of a function $f$ under a Gaussian distribution with mean $x_0$ and standard deviation $\sigma$.
We prove that if $f$ equals its Taylor series expansion everywhere and the series is integrable term-by-term (which holds for functions with appropriate growth bounds), then the expected value is given by the series:
$$ \mathbb{E}[f(X)] = \sum_{k=0}^\infty \frac{f^{(2k)}(x_0)}{k!} \left(\frac{\sigma^2}{2}\right)^k $$
This is derived by expanding $f$ around $x_0$, using the fact that odd central moments of the Gaussian are zero, and even central moments are given by $\sigma^{2k} (2k-1)!!$.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check ProbabilityTheory.moment
#check ProbabilityTheory.gaussianReal
#check iteratedDeriv

#check AnalyticOn
#check Nat.factorial
#check sq_nonneg

/-
The series expansion for the expected value of f under a Gaussian distribution.
-/
open MeasureTheory ProbabilityTheory

noncomputable def gaussianExpectedValueExpansion (f : ℝ → ℝ) (x₀ σ : ℝ) : ℝ :=
  ∑' k : ℕ, (iteratedDeriv (2 * k) f x₀) * (σ ^ (2 * k)) / ((2 : ℝ) ^ k * (k.factorial : ℝ))

/-
The integral of x^(2n+1) times the standard Gaussian PDF over the reals is 0.
-/
open MeasureTheory ProbabilityTheory Real

lemma integral_pow_mul_gaussianPDF_eq_zero_of_odd (n : ℕ) :
    ∫ x, x ^ (2 * n + 1) * gaussianPDFReal 0 1 x = 0 := by
  -- We'll use the fact that the integral of an odd function over the entire real line is zero.
  have h_odd : ∀ f : ℝ → ℝ, (∀ x, f (-x) = -f x) → ∫ x, f x = 0 := by
    -- By definition of odd functions, we know that $\int_{-\infty}^{\infty} f(x) \, dx = \int_{-\infty}^{\infty} -f(x) \, dx$.
    intro f hf
    have h_integral : ∫ x, f x = ∫ x, -f x := by
      rw [ ← funext hf, MeasureTheory.integral_neg_eq_self ];
    rw [ MeasureTheory.integral_neg ] at h_integral ; linarith;
  norm_num [ h_odd, ProbabilityTheory.gaussianPDFReal ] at * ; ring_nf at * ; aesop;

/-
The even moments of the standard Gaussian are (2n)! / (2^n * n!).
-/
open MeasureTheory ProbabilityTheory Real

lemma integral_pow_mul_gaussianPDF_eq_even (n : ℕ) :
    ∫ x, x ^ (2 * n) * gaussianPDFReal 0 1 x = (2 * n).factorial / (2 ^ n * n.factorial) := by
  -- We'll use the fact that $\int_{-\infty}^{\infty} x^{2n} e^{-x^2/2} \, dx = \sqrt{2\pi} \cdot \frac{(2n)!}{2^n n!}$.
  have h_gauss_integral : ∫ x : ℝ, x ^ (2 * n) * Real.exp (-x ^ 2 / 2) = Real.sqrt (2 * Real.pi) * (Nat.factorial (2 * n)) / (2 ^ n * Nat.factorial n) := by
    have := @integral_rpow_mul_exp_neg_mul_rpow;
    -- We'll use the fact that $\int_{-\infty}^{\infty} x^{2n} e^{-x^2/2} \, dx = \sqrt{2\pi} \cdot \frac{(2n)!}{2^n n!}$ to simplify the expression.
    have h_gauss_integral : ∫ x in Set.Ioi 0, x ^ (2 * n) * Real.exp (-x ^ 2 / 2) = Real.sqrt (2 * Real.pi) * (Nat.factorial (2 * n)) / (2 ^ (n + 1) * Nat.factorial n) := by
      convert @this 2 ( 2 * n ) ( 1 / 2 ) ( by norm_num ) ( by linarith ) ( by norm_num ) using 1 <;> norm_num [ div_eq_inv_mul ];
      · norm_cast;
      · -- Now use the fact that $\Gamma(n + 1/2) = \frac{(2n)!}{4^n n!} \sqrt{\pi}$.
        have h_gamma : Real.Gamma (n + 1 / 2) = (Nat.factorial (2 * n)) / (4 ^ n * Nat.factorial n) * Real.sqrt Real.pi := by
          induction' n with n ih;
          · simpa using congr_arg ( ( ↑ ) : ℝ → ℂ ) Real.Gamma_one_half_eq;
          · rw [ Nat.cast_succ, add_right_comm, Real.Gamma_add_one ( by positivity ), ih ] ; push_cast [ Nat.factorial_succ, Nat.mul_succ ] ; ring;
            -- Combine and simplify the terms on the right-hand side.
            field_simp
            ring;
            simpa using by ring;
        field_simp;
        rw [ show ( 2 * n + 1 : ℝ ) / 2 = n + 1 / 2 by ring ] ; rw [ h_gamma ] ; ring;
        norm_num [ Real.rpow_sub, Real.rpow_neg, mul_assoc, mul_left_comm, mul_comm, Nat.factorial_ne_zero ] ; ring;
        norm_num [ ← Real.sqrt_eq_rpow, mul_assoc, ← mul_pow ];
    -- Since the integrand is even, we can double the integral over $(0, \infty)$ to get the integral over $(-\infty, \infty)$.
    have h_even : ∫ x in Set.Iic 0, x ^ (2 * n) * Real.exp (-x ^ 2 / 2) = Real.sqrt (2 * Real.pi) * (Nat.factorial (2 * n)) / (2 ^ (n + 1) * Nat.factorial n) := by
      rw [ ← h_gauss_integral, ← neg_zero, ← integral_comp_neg_Iic ] ; norm_num;
    convert congr_arg₂ ( · + · ) h_even h_gauss_integral using 1;
    · rw [ ← MeasureTheory.setIntegral_union ] <;> norm_num;
      · exact ( by contrapose! h_even; rw [ MeasureTheory.integral_undef h_even ] ; positivity );
      · exact ( by contrapose! h_gauss_integral; rw [ MeasureTheory.integral_undef h_gauss_integral ] ; positivity );
    · ring;
  convert congr_arg ( · * ( Real.sqrt ( 2 * Real.pi ) ) ⁻¹ ) h_gauss_integral using 1 <;> norm_num [ ProbabilityTheory.gaussianPDFReal ];
  · rw [ ← MeasureTheory.integral_mul_const ] ; congr ; ext ; ring;
  · -- By simplifying, we can see that the two expressions are equal.
    field_simp [mul_comm, mul_assoc, mul_left_comm]

/-
The integral of (x - x0)^k against the Gaussian PDF with mean x0 and variance sigma^2 is sigma^k times the integral of x^k against the standard Gaussian PDF.
-/
open MeasureTheory ProbabilityTheory Real

lemma integral_mul_gaussianPDFReal_sub_pow (x₀ σ : ℝ) (k : ℕ) (hσ : 0 < σ) :
    ∫ x, (x - x₀) ^ k * gaussianPDFReal x₀ ⟨σ ^ 2, by positivity⟩ x =
    σ ^ k * ∫ x, x ^ k * gaussianPDFReal 0 1 x := by
  rw [ ← MeasureTheory.integral_const_mul ] ; norm_num [ ProbabilityTheory.gaussianPDFReal ] ; ring;
  -- Perform the substitution $u = \frac{x - x₀}{\sigma}$ to simplify the integral.
  have h_subst : ∀ {g : ℝ → ℝ}, ∫ x, g x = ∫ u, g (u * σ + x₀) * σ := by
    intro g; rw [ MeasureTheory.integral_mul_const ] ; rw [ MeasureTheory.Measure.integral_comp_mul_right ( fun x => g ( x + x₀ ) ) ] ; norm_num [ hσ.ne' ] ; ring;
    rw [ abs_of_pos hσ, inv_mul_eq_div, div_mul_cancel₀ _ hσ.ne', MeasureTheory.integral_add_right_eq_self ];
  convert h_subst using 3 ; ring ; norm_num [ hσ.le ] ; ring;
  grind

#check integral_withDensity_eq_integral_toReal_smul

/-
The integral of f with respect to the Gaussian measure is the integral of f times the Gaussian PDF.
-/
open MeasureTheory ProbabilityTheory Real

lemma integral_gaussianReal_eq_integral_mul_pdf (μ : ℝ) (v : NNReal) (hv : v ≠ 0) (f : ℝ → ℝ) :
    ∫ x, f x ∂(gaussianReal μ v) = ∫ x, f x * gaussianPDFReal μ v x := by
  convert integral_withDensity_eq_integral_toReal_smul _ _ _ using 1;
  convert rfl;
  rotate_left;
  rotate_left;
  exact MeasureTheory.MeasureSpace.volume;
  exact fun x => ENNReal.ofReal ( ProbabilityTheory.gaussianPDFReal μ v x );
  · refine' Measurable.ennreal_ofReal _;
    exact Measurable.mul ( measurable_const ) ( Measurable.exp ( by exact Measurable.div_const ( by exact Measurable.neg ( by exact Measurable.pow_const ( by exact measurable_id.sub_const μ ) _ ) ) _ ) );
  · exact Filter.Eventually.of_forall fun x => ENNReal.ofReal_lt_top;
  · unfold ProbabilityTheory.gaussianReal;
    unfold ProbabilityTheory.gaussianPDF; aesop;
  · simp +decide [ mul_comm, ENNReal.toReal_ofReal ( ProbabilityTheory.gaussianPDFReal_nonneg _ _ _ ) ]

/-
The k-th central moment of a Gaussian with standard deviation sigma is sigma^k times the k-th moment of the standard Gaussian.
-/
open MeasureTheory ProbabilityTheory Real

lemma integral_sub_pow_gaussianReal (x₀ σ : ℝ) (k : ℕ) (hσ : 0 < σ) :
    ∫ x, (x - x₀) ^ k ∂(gaussianReal x₀ ⟨σ^2, by positivity⟩) =
    σ ^ k * ∫ x, x ^ k ∂(gaussianReal 0 1) := by
  convert integral_mul_gaussianPDFReal_sub_pow x₀ σ k hσ using 1;
  · convert integral_gaussianReal_eq_integral_mul_pdf _ _ _ _ using 1;
    exact ne_of_gt ( Subtype.mk_lt_mk.mpr ( sq_pos_of_pos hσ ) );
  · rw [ integral_gaussianReal_eq_integral_mul_pdf ];
    norm_num

/-
The k-th moment of the standard Gaussian distribution is 0 if k is odd, and (k)! / (2^(k/2) * (k/2)!) if k is even.
-/
open MeasureTheory ProbabilityTheory Real

lemma integral_pow_gaussianReal_zero_one (k : ℕ) :
    ∫ x, x ^ k ∂(gaussianReal 0 1) = if Even k then (k.factorial : ℝ) / (2 ^ (k / 2) * (k / 2).factorial) else 0 := by
  have h_moment : ∫ x, x ^ k ∂(gaussianReal 0 1) = ∫ x, x ^ k * gaussianPDFReal 0 1 x := by
    convert integral_gaussianReal_eq_integral_mul_pdf _ _ _ _ using 1 ; norm_num;
  rcases Nat.even_or_odd' k with ⟨ c, rfl | rfl ⟩ <;> norm_num [ h_moment ];
  · convert integral_pow_mul_gaussianPDF_eq_even c using 1;
  · convert integral_pow_mul_gaussianPDF_eq_zero_of_odd c using 1

#check Nat.even_mul
#check Nat.even_add_one
#check Nat.not_even_bit1

#check even_two_mul
#check Nat.not_even_two_mul_add_one

/-
The (2k+1)-th term of the Gaussian series expansion is 0.
-/
open MeasureTheory ProbabilityTheory Real

noncomputable def gaussianSeriesTerm (f : ℝ → ℝ) (x₀ σ : ℝ) (k : ℕ) : ℝ :=
  (iteratedDeriv k f x₀) / k.factorial * ∫ x, (x - x₀) ^ k ∂(gaussianReal x₀ ⟨σ^2, sq_nonneg σ⟩)

lemma gaussianSeriesTerm_odd (f : ℝ → ℝ) (x₀ σ : ℝ) (k : ℕ) (hσ : 0 < σ) :
    gaussianSeriesTerm f x₀ σ (2 * k + 1) = 0 := by
      convert congr_arg _ ( integral_sub_pow_gaussianReal x₀ σ ( 2 * k + 1 ) hσ ) using 1;
      rw [ integral_pow_gaussianReal_zero_one ] ; norm_num [ Nat.factorial_ne_zero, hσ.ne' ]

#check gaussianSeriesTerm
#check gaussianSeriesTerm_odd

/-
The (2k)-th term of the Gaussian series expansion matches the expected formula.
-/
open MeasureTheory ProbabilityTheory Real

lemma gaussianSeriesTerm_even (f : ℝ → ℝ) (x₀ σ : ℝ) (k : ℕ) (hσ : 0 < σ) :
    gaussianSeriesTerm f x₀ σ (2 * k) =
    (iteratedDeriv (2 * k) f x₀) * (σ ^ (2 * k)) / ((2 : ℝ) ^ k * (k.factorial : ℝ)) := by
      convert congr_arg _ ( integral_sub_pow_gaussianReal x₀ σ ( 2 * k ) hσ ) using 1;
      rw [ integral_pow_gaussianReal_zero_one ] ; norm_num [ Nat.even_mul, div_mul_eq_mul_div ] ; ring;
      norm_num [ Nat.factorial_ne_zero ]

/-
The sum of the Gaussian series terms equals the expected value expansion.
-/
open MeasureTheory ProbabilityTheory Real

lemma sum_gaussianSeriesTerm_eq_expansion (f : ℝ → ℝ) (x₀ σ : ℝ) (hσ : 0 < σ)
    (h_sum : Summable (fun k ↦ (iteratedDeriv (2 * k) f x₀) * (σ ^ (2 * k)) / ((2 : ℝ) ^ k * (k.factorial : ℝ)))) :
    ∑' k, gaussianSeriesTerm f x₀ σ k = gaussianExpectedValueExpansion f x₀ σ := by
      convert ( Summable.hasSum <| h_sum ) |> HasSum.tsum_eq using 1;
      rw [ ← tsum_even_add_odd ];
      · simp_all +decide [ gaussianSeriesTerm_even, gaussianSeriesTerm_odd ];
      · convert h_sum using 1;
        exact funext fun k => gaussianSeriesTerm_even f x₀ σ k hσ;
      · exact ⟨ _, hasSum_single 0 fun k hk => by rw [ show gaussianSeriesTerm f x₀ σ ( 2 * k + 1 ) = 0 from gaussianSeriesTerm_odd f x₀ σ k hσ ] ⟩

/-
The expected value of f under a Gaussian distribution equals its series expansion, assuming the Taylor series converges to f and termwise integration is valid.
-/
open MeasureTheory ProbabilityTheory Real

theorem gaussian_expected_value_eq_expansion (f : ℝ → ℝ) (x₀ σ : ℝ)
    (hσ : 0 < σ)
    (h_eq_sum : ∀ x, f x = ∑' k, (iteratedDeriv k f x₀) / k.factorial * (x - x₀) ^ k)
    (h_abs_sum : Summable (fun k ↦ ∫ x, |(iteratedDeriv k f x₀) / k.factorial * (x - x₀) ^ k| ∂(gaussianReal x₀ ⟨σ^2, sq_nonneg σ⟩)))
    (h_sum : Summable (fun k ↦ (iteratedDeriv (2 * k) f x₀) * (σ ^ (2 * k)) / ((2 : ℝ) ^ k * (k.factorial : ℝ)))) :
    ∫ x, f x ∂(gaussianReal x₀ ⟨σ^2, sq_nonneg σ⟩) = gaussianExpectedValueExpansion f x₀ σ := by
      -- Apply the dominated convergence theorem to interchange the summation and integral.
      have h_interchange : ∫ x, ∑' k, (iteratedDeriv k f x₀) / (k.factorial : ℝ) * (x - x₀) ^ k ∂(gaussianReal x₀ ⟨σ^2, sq_nonneg σ⟩) = ∑' k, ∫ x, (iteratedDeriv k f x₀) / (k.factorial : ℝ) * (x - x₀) ^ k ∂(gaussianReal x₀ ⟨σ^2, sq_nonneg σ⟩) := by
        rw [ MeasureTheory.integral_tsum ];
        · exact fun k => Continuous.aestronglyMeasurable ( by continuity );
        · refine' ne_of_lt ( lt_of_le_of_lt ( ENNReal.tsum_le_tsum fun k => _ ) _ );
          use fun k => ENNReal.ofReal ( ∫ x, |iteratedDeriv k f x₀ / ( k.factorial : ℝ ) * ( x - x₀ ) ^ k| ∂ProbabilityTheory.gaussianReal x₀ ⟨ σ ^ 2, sq_nonneg σ ⟩ );
          · rw [ MeasureTheory.ofReal_integral_eq_lintegral_ofReal ];
            · field_simp;
              refine' MeasureTheory.lintegral_mono fun x => _;
              rw [ ENNReal.le_ofReal_iff_toReal_le ] <;> norm_num;
              norm_num [ abs_div, abs_mul ];
            · refine' MeasureTheory.Integrable.abs _;
              refine' MeasureTheory.Integrable.const_mul _ _;
              have h_integrable : ∀ k : ℕ, MeasureTheory.Integrable (fun x => x ^ k) (ProbabilityTheory.gaussianReal 0 ⟨σ ^ 2, sq_nonneg σ⟩) := by
                intro k;
                have h_gauss_integrable : MeasureTheory.Integrable (fun x => x ^ k * Real.exp (-x ^ 2 / (2 * σ ^ 2))) MeasureTheory.volume := by
                  have := @integrable_rpow_mul_exp_neg_mul_sq;
                  convert @this ( 1 / ( 2 * σ ^ 2 ) ) ( by positivity ) ( k : ℝ ) ( by linarith ) using 3 ; ring;
                  · norm_cast;
                  · ring;
                rw [ ProbabilityTheory.gaussianReal ];
                rw [ if_neg ( by exact ne_of_apply_ne Subtype.val ( by positivity ) ) ];
                rw [ MeasureTheory.integrable_withDensity_iff ];
                · convert h_gauss_integrable.mul_const ( 1 / ( Real.sqrt ( 2 * Real.pi ) * σ ) ) using 2 ; norm_num [ ProbabilityTheory.gaussianPDF ] ; ring;
                  norm_num [ ProbabilityTheory.gaussianPDFReal ] ; ring;
                  rw [ ENNReal.toReal_ofReal ( Real.exp_nonneg _ ) ] ; norm_num [ hσ.le ] ; ring;
                · fun_prop;
                · simp [ProbabilityTheory.gaussianPDF];
              have h_integrable : MeasureTheory.Integrable (fun x => x ^ k) (MeasureTheory.Measure.map (fun x => x - x₀) (ProbabilityTheory.gaussianReal x₀ ⟨σ ^ 2, sq_nonneg σ⟩)) := by
                convert h_integrable k using 1;
                ext; simp [ProbabilityTheory.gaussianReal];
                split_ifs <;> simp_all +decide [ ProbabilityTheory.gaussianPDF ];
                · exact absurd ‹_› ( by exact ne_of_gt ( Subtype.mk_lt_mk.mpr ( sq_pos_of_pos hσ ) ) );
                · rw [ MeasureTheory.Measure.map_apply ];
                  · rw [ MeasureTheory.withDensity_apply' ];
                    rw [ ← MeasureTheory.lintegral_indicator, ← MeasureTheory.lintegral_indicator ];
                    · simp +decide [ Set.indicator, ProbabilityTheory.gaussianPDFReal ];
                      rw [ ← MeasureTheory.lintegral_add_right_eq_self _ x₀ ] ; congr ; ext ; simp +decide [ ProbabilityTheory.gaussianPDF ];
                      simp +decide [ ProbabilityTheory.gaussianPDFReal, ProbabilityTheory.gaussianPDF ];
                    · assumption;
                    · exact measurable_id.sub_const x₀ ‹_›;
                  · exact measurable_id.sub measurable_const;
                  · assumption;
              rw [ MeasureTheory.integrable_map_measure ] at h_integrable ; tauto;
              · exact h_integrable.1;
              · exact measurable_id.sub measurable_const |> Measurable.aemeasurable;
            · exact Filter.Eventually.of_forall fun x => abs_nonneg _;
          · exact?;
      convert h_interchange using 1;
      · simpa only [ ← h_eq_sum ];
      · field_simp;
        convert sum_gaussianSeriesTerm_eq_expansion f x₀ σ hσ h_sum |> Eq.symm using 1;
        exact tsum_congr fun k => by rw [ show gaussianSeriesTerm f x₀ σ k = ( iteratedDeriv k f x₀ ) / ( k.factorial : ℝ ) * ∫ x, ( x - x₀ ) ^ k ∂ ( ProbabilityTheory.gaussianReal x₀ ⟨ σ ^ 2, sq_nonneg σ ⟩ ) by rfl ] ; rw [ ← MeasureTheory.integral_const_mul ] ; congr; ext; ring;

/-
The integral of f under a Gaussian distribution equals the sum of the integrals of its Taylor series terms, assuming convergence.
-/
open MeasureTheory ProbabilityTheory Real

lemma integral_gaussian_eq_sum_gaussianSeriesTerm (f : ℝ → ℝ) (x₀ σ : ℝ)
    (hσ : 0 < σ)
    (h_eq_sum : ∀ x, f x = ∑' k, (iteratedDeriv k f x₀) / k.factorial * (x - x₀) ^ k)
    (h_abs_sum : Summable (fun k ↦ ∫ x, |(iteratedDeriv k f x₀) / k.factorial * (x - x₀) ^ k| ∂(gaussianReal x₀ ⟨σ^2, sq_nonneg σ⟩))) :
    ∫ x, f x ∂(gaussianReal x₀ ⟨σ^2, sq_nonneg σ⟩) = ∑' k, gaussianSeriesTerm f x₀ σ k := by
      rw [ show ( ∫ x, f x ∂ ( ProbabilityTheory.gaussianReal x₀ ⟨ σ ^ 2, sq_nonneg σ ⟩ ) ) = ∑' k, ∫ x, ( iteratedDeriv k f x₀ / ( k.factorial : ℝ ) ) * ( x - x₀ ) ^ k ∂ ( ProbabilityTheory.gaussianReal x₀ ⟨ σ ^ 2, sq_nonneg σ ⟩ ) from ?_ ];
      · exact tsum_congr fun k => by unfold gaussianSeriesTerm; simp +decide [ div_eq_mul_inv, mul_assoc, MeasureTheory.integral_const_mul ] ;
      · rw [ funext h_eq_sum, MeasureTheory.integral_tsum ];
        · simp +decide only [← h_eq_sum];
        · exact fun k => Continuous.aestronglyMeasurable ( by fun_prop );
        · refine' ne_of_lt ( lt_of_le_of_lt ( ENNReal.tsum_le_tsum fun k => _ ) _ );
          use fun k => ENNReal.ofReal ( ∫ x, |iteratedDeriv k f x₀ / ( k.factorial : ℝ ) * ( x - x₀ ) ^ k| ∂ProbabilityTheory.gaussianReal x₀ ⟨ σ ^ 2, sq_nonneg σ ⟩ );
          · rw [ MeasureTheory.ofReal_integral_eq_lintegral_ofReal ];
            · refine' MeasureTheory.lintegral_mono fun x => _;
              rw [ ENNReal.le_ofReal_iff_toReal_le ] <;> norm_num;
              · norm_num [ abs_div ];
              · exact?;
              · positivity;
            · -- The function inside the integral is a polynomial times a Gaussian, which is integrable.
              have h_integrable : MeasureTheory.Integrable (fun x => (x - x₀) ^ k) (ProbabilityTheory.gaussianReal x₀ ⟨σ ^ 2, sq_nonneg σ⟩) := by
                have h_integrable : ∀ m : ℕ, MeasureTheory.Integrable (fun x => x ^ m) (ProbabilityTheory.gaussianReal 0 ⟨σ ^ 2, sq_nonneg σ⟩) := by
                  intro m;
                  have h_gauss_integrable : MeasureTheory.Integrable (fun x => x ^ m * Real.exp (-x ^ 2 / (2 * σ ^ 2))) MeasureTheory.volume := by
                    have := @integrable_rpow_mul_exp_neg_mul_sq;
                    convert @this ( 1 / ( 2 * σ ^ 2 ) ) ( by positivity ) ( m : ℝ ) ( by linarith ) using 3 ; ring;
                    · norm_cast;
                    · ring;
                  rw [ ProbabilityTheory.gaussianReal ];
                  rw [ if_neg ( by exact ne_of_apply_ne Subtype.val ( by positivity ) ) ];
                  rw [ MeasureTheory.integrable_withDensity_iff ];
                  · convert h_gauss_integrable.mul_const ( 1 / ( Real.sqrt ( 2 * Real.pi ) * σ ) ) using 2 ; norm_num [ ProbabilityTheory.gaussianPDF ] ; ring;
                    norm_num [ ProbabilityTheory.gaussianPDFReal ] ; ring;
                    rw [ ENNReal.toReal_ofReal ( Real.exp_nonneg _ ) ] ; norm_num [ hσ.le ] ; ring;
                  · exact?;
                  · simp [ProbabilityTheory.gaussianPDF];
                have h_integrable : MeasureTheory.Integrable (fun x => (x - x₀) ^ k) (MeasureTheory.Measure.map (fun x => x + x₀) (ProbabilityTheory.gaussianReal 0 ⟨σ ^ 2, sq_nonneg σ⟩)) := by
                  rw [ MeasureTheory.integrable_map_measure ];
                  · convert h_integrable k using 1;
                    exact funext fun x => by simp +decide ;
                  · exact Continuous.aestronglyMeasurable ( by continuity );
                  · exact measurable_id.add_const x₀ |> Measurable.aemeasurable;
                convert h_integrable using 1;
                ext; simp [ProbabilityTheory.gaussianReal];
                field_simp;
                split_ifs <;> simp_all +decide [ ProbabilityTheory.gaussianPDF ];
                rw [ MeasureTheory.Measure.map_apply ];
                · rw [ MeasureTheory.withDensity_apply' ];
                  rw [ ← MeasureTheory.lintegral_indicator, ← MeasureTheory.lintegral_indicator ];
                  · simp +decide [ Set.indicator, ProbabilityTheory.gaussianPDFReal, ProbabilityTheory.gaussianPDF ];
                    rw [ ← MeasureTheory.lintegral_add_right_eq_self _ x₀ ] ; congr ; ext ; ring;
                  · exact measurable_id.add_const x₀ ‹_›;
                  · assumption;
                · exact measurable_id.add_const _;
                · assumption;
              simpa only [ abs_mul, abs_div, abs_of_nonneg ( by positivity : ( 0 : ℝ ) ≤ k.factorial ) ] using h_integrable.norm.const_mul _;
            · exact Filter.Eventually.of_forall fun x => abs_nonneg _;
          · rw [ ← ENNReal.ofReal_tsum_of_nonneg ] <;> norm_num [ h_abs_sum ];
            · exact fun k => MeasureTheory.integral_nonneg fun x => by positivity;
            · convert h_abs_sum using 2 ; norm_num [ abs_mul, abs_div ]