[program:base64-rs-worker]
command=/home/x/Dropbox/2/src/rust/base64-rs-worker/target/debug/base64-rs-worker
directory=/home/x/Dropbox/2/src/rust/base64-rs-worker
user=x
autostart=true
autorestart=true
stderr_logfile=/var/log/rs-worker/base64.err.log
stdout_logfile=/var/log/rs-worker/base64.out.log
