[program:openrouter-rs-worker]
command=/home/x/Dropbox/2/src/rust/openrouter-rs-worker/target/debug/openrouter-rs-worker
directory=/home/x/Dropbox/2/src/rust/openrouter-rs-worker
user=x
autostart=true
autorestart=true
stderr_logfile=/var/log/rs-worker/openrouter.err.log
stdout_logfile=/var/log/rs-worker/openrouter.out.log
