[program:nanogpt-rs-worker]
command=/home/x/Dropbox/2/src/rust/nanogpt-rs-worker/target/debug/nanogpt-rs-worker
directory=/home/x/Dropbox/2/src/rust/nanogpt-rs-worker
user=x
autostart=true
autorestart=true
stderr_logfile=/var/log/rs-worker/nanogpt.err.log
stdout_logfile=/var/log/rs-worker/nanogpt.out.log
